const services=[
{id:"passport",name:"Passport Information",category:"Identity",icon:"🛂",desc:"Find passport application guidance and the responsible government department.",agency:"Department of Passports",url:"https://nepalpassport.gov.np/",scope:"Federal"},
{id:"pan",name:"PAN Registration",category:"Tax",icon:"🧾",desc:"Find information about Personal and Business Permanent Account Numbers.",agency:"Inland Revenue Department",url:"https://ird.gov.np/",scope:"Federal"},
{id:"company",name:"Company Registration",category:"Business",icon:"🏢",desc:"Find official company registration information and requirements.",agency:"Office of Company Registrar",url:"https://ocr.gov.np/",scope:"Federal"},
{id:"license",name:"Driving License",category:"Transport",icon:"🚗",desc:"Find driving license information. Available offices and processes can vary by province.",agency:"Department of Transport Management",url:"https://dotm.gov.np/",scope:"Provincial"},
{id:"nid",name:"National Identity Card",category:"Identity",icon:"🪪",desc:"Find official information about national identity card services.",agency:"Department of National ID and Civil Registration",url:"https://donidcr.gov.np/",scope:"Federal"},
{id:"birth",name:"Birth Registration",category:"Civil Registration",icon:"👶",desc:"Learn where to start with civil registration through local government.",agency:"Local Government / DONIDCR",url:"https://donidcr.gov.np/",scope:"Local"}
];
const provinces=["Koshi","Madhesh","Bagmati","Gandaki","Lumbini","Karnali","Sudurpashchim"];
let query="",category="All",province="";
const $=id=>document.getElementById(id);
function setSearch(v){query=v.trim().toLowerCase();render();document.getElementById("services").scrollIntoView({behavior:"smooth"});}
function render(){const cats=["All",...new Set(services.map(s=>s.category))];$("filters").innerHTML=cats.map(c=>'<button class="filter '+(category===c?'active':'')+'" data-cat="'+c+'">'+c+'</button>').join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{category=b.dataset.cat;render()});const results=services.filter(s=>(category==="All"||s.category===category)&&(!query||[s.name,s.desc,s.agency,s.category].join(" ").toLowerCase().includes(query)));$("serviceGrid").innerHTML=results.length?results.map(s=>'<button class="card service" data-id="'+s.id+'"><div class="symbol">'+s.icon+'</div><span class="tag">'+s.category+'</span><h3>'+s.name+'</h3><p>'+s.desc+'</p><footer>View service details →</footer></button>').join(""):'<div class="empty">No matching services in this demonstration. Try a different search.</div>';document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>showService(b.dataset.id));$("resultCount").textContent=results.length+" service"+(results.length===1?"":"s")+" available in this demo";$("provinces").innerHTML=provinces.map(p=>'<button class="province '+(p===province?'active':'')+'" data-province="'+p+'">'+p+' <span>→</span></button>').join("");document.querySelectorAll("[data-province]").forEach(b=>b.onclick=()=>{province=b.dataset.province;$("provinceMessage").textContent=province+" selected. Province-specific office records will be added after source verification.";render()})}
function showService(id){const s=services.find(x=>x.id===id);$("detail").innerHTML='<button class="close" id="closeDetail" aria-label="Close">✕</button><div class="symbol">'+s.icon+'</div><span class="tag">'+s.category+'</span><h2>'+s.name+'</h2><p class="muted">'+s.desc+'</p><p><strong>Responsible organization:</strong> '+s.agency+'</p><p><strong>Scope:</strong> '+s.scope+'</p><p><strong>Source:</strong> Official department website; verify current procedures there.</p><p><a href="'+s.url+'" target="_blank" rel="noopener noreferrer">Open government website ↗</a></p><p class="muted">This demo does not provide verified document lists, fees, or processing times.</p>';$("modal").classList.add("show");$("closeDetail").onclick=closeModal;}
function closeModal(){$("modal").classList.remove("show")}
document.addEventListener("DOMContentLoaded",()=>{$("searchForm").onsubmit=e=>{e.preventDefault();setSearch($("searchInput").value)};$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});render()});