// First-party commission homepages and application portals inspected 2026-10-09.
// These links verify the institution and portal destination only, NOT open vacancies,
// eligibility, local hiring authority, current fees or applicant account availability.
// Never collect candidate passwords or personal information in PublicInfoHub.
const LOKSEWA_PORTALS = [
 {id:"federal",level:"Federal",province:"",name:"Public Service Commission (Nepal)",nameNe:"लोक सेवा आयोग (नेपाल)",website:"https://psc.gov.np/",applyUrl:null,sourceUrl:"https://psc.gov.np/",note:"Check the federal commission for central-government vacancies, advertisements, syllabuses, exam centres and results."},
 {id:"koshi",level:"Provincial",province:"Koshi",name:"Koshi Province Public Service Commission",nameNe:"प्रदेश लोक सेवा आयोग, कोशी",website:"https://psc.koshi.gov.np/",applyUrl:"https://psconline.koshi.gov.np/login",sourceUrl:"https://psc.koshi.gov.np/",note:"Province and qualifying local-service recruitment notices; confirm each vacancy's recruiting authority."},
 {id:"madhesh",level:"Provincial",province:"Madhesh",name:"Madhesh Province Public Service Commission",nameNe:"प्रदेश लोक सेवा आयोग, मधेश",website:"https://ppsc.madhesh.gov.np/",applyUrl:"https://ppsconline.p2.gov.np/login",sourceUrl:"https://ppsc.madhesh.gov.np/category/application-form/",note:"Official advertisements, syllabuses and application guidance. Use the official commission website to confirm current vacancy instructions."},
 {id:"bagmati",level:"Provincial",province:"Bagmati",name:"Bagmati Province Public Service Commission",nameNe:"प्रदेश लोक सेवा आयोग, बागमती",website:"https://spsc.bagamati.gov.np/",applyUrl:"https://ppsconline.bagamati.gov.np/login",sourceUrl:"https://spsc.bagamati.gov.np/category/forms/",note:"Official commission website and recruitment notices. Use its online application portal for the relevant advertised vacancy."},
 {id:"gandaki",level:"Provincial",province:"Gandaki",name:"Gandaki Province Public Service Commission",nameNe:"प्रदेश लोक सेवा आयोग, गण्डकी",website:"https://ppsc.gandaki.gov.np/",applyUrl:"https://onlineppsc.gandaki.gov.np/login",sourceUrl:"https://ppsc.gandaki.gov.np/online_services",note:"Official website offers online-services navigation; check the official recruitment notice before applying."},
 {id:"lumbini",level:"Provincial",province:"Lumbini",name:"Lumbini Province Public Service Commission",nameNe:"प्रदेश लोक सेवा आयोग, लुम्बिनी",website:"https://ppsc.lumbini.gov.np/",applyUrl:"https://ppsconline.lumbini.gov.np/login",sourceUrl:"https://ppsc.lumbini.gov.np/",note:"Check official provincial and applicable local recruitment announcements before submitting."},
 {id:"karnali",level:"Provincial",province:"Karnali",name:"Karnali Province Public Service Commission",nameNe:"प्रदेश लोक सेवा आयोग, कर्णाली",website:"https://ppsc.karnali.gov.np/",applyUrl:"https://ppsconline.karnali.gov.np/",sourceUrl:"https://ppsc.karnali.gov.np/",note:"Check the official notice and syllabus for the advertised government-service level."},
 {id:"sudurpashchim",level:"Provincial",province:"Sudurpashchim",name:"Sudurpashchim Province Public Service Commission",nameNe:"प्रदेश लोक सेवा आयोग, सुदूरपश्चिम",website:"https://psc.sudurpashchim.gov.np/",applyUrl:"https://ppsconline.sudurpashchim.gov.np/",sourceUrl:"https://psc.sudurpashchim.gov.np/",note:"Official commission and online application system; local-service eligibility depends on the specific advertisement."}
];
const LOKSEWA_CHECKED_ON="2026-10-09";
