// Publicly verifiable central-government department homepages, checked 2026-10-09.
// "verified" covers organization identity and official homepage ONLY.
// It does not certify fees, application rules, branch availability or live uptime.
// Each record's sourceUrl is the first-party government website inspected.
const GOVERNMENT_OFFICES = [
  { id:"department-passports",name:"Department of Passports",nameNe:"राहदानी विभाग",category:"Identity",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Tripureshwor, Kathmandu",description:"Official source for Nepal passport information and notices.",website:"https://nepalpassport.gov.np/",sourceUrl:"https://nepalpassport.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"inland-revenue",name:"Inland Revenue Department",nameNe:"आन्तरिक राजस्व विभाग",category:"Tax",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Lazimpat, Kathmandu",description:"Official national tax administration and taxpayer service information.",website:"https://ird.gov.np/",sourceUrl:"https://ird.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"company-registrar",name:"Office of Company Registrar",nameNe:"कम्पनी रजिष्ट्रारको कार्यालय",category:"Business",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Tripureshwor, Kathmandu",description:"Official company registration and company administration information.",website:"https://ocr.gov.np/",sourceUrl:"https://ocr.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"transport-management",name:"Department of Transport Management",nameNe:"यातायात व्यवस्था विभाग",category:"Transport",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Minbhawan, Kathmandu",description:"Official transport-management information; local licensing arrangements can vary.",website:"https://dotm.gov.np/",sourceUrl:"https://dotm.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"national-id-civil-reg",name:"Department of National ID and Civil Registration",nameNe:"राष्ट्रिय परिचयपत्र तथा पञ्जीकरण विभाग",category:"Identity",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Singha Durbar, Kathmandu",description:"Official source for national identity and civil registration information.",website:"https://donidcr.gov.np/",sourceUrl:"https://donidcr.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" }
];
