// Publicly verifiable central-government department homepages, checked 2026-10-09.
// "verified" covers organization identity and official homepage ONLY.
// It does not certify fees, application rules, branch availability or live uptime.
// Each record's sourceUrl is the first-party government website inspected.
// Phase 5 adds one first-party municipal homepage from each previously unrepresented province.
const GOVERNMENT_OFFICES = [
  { id:"department-passports",name:"Department of Passports",nameNe:"राहदानी विभाग",category:"Identity",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Tripureshwor, Kathmandu",description:"Official source for Nepal passport information and notices.",website:"https://nepalpassport.gov.np/",sourceUrl:"https://nepalpassport.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"inland-revenue",name:"Inland Revenue Department",nameNe:"आन्तरिक राजस्व विभाग",category:"Tax",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Lazimpat, Kathmandu",description:"Official national tax administration and taxpayer service information.",website:"https://ird.gov.np/",sourceUrl:"https://ird.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"company-registrar",name:"Office of Company Registrar",nameNe:"कम्पनी रजिष्ट्रारको कार्यालय",category:"Business",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Tripureshwor, Kathmandu",description:"Official company registration and company administration information.",website:"https://ocr.gov.np/",sourceUrl:"https://ocr.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"transport-management",name:"Department of Transport Management",nameNe:"यातायात व्यवस्था विभाग",category:"Transport",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Minbhawan, Kathmandu",description:"Official transport-management information; local licensing arrangements can vary.",website:"https://dotm.gov.np/",sourceUrl:"https://dotm.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"national-id-civil-reg",name:"Department of National ID and Civil Registration",nameNe:"राष्ट्रिय परिचयपत्र तथा पञ्जीकरण विभाग",category:"Identity",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Singha Durbar, Kathmandu",description:"Official source for national identity and civil registration information.",website:"https://donidcr.gov.np/",sourceUrl:"https://donidcr.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"survey-department",name:"Department of Survey",nameNe:"नापी विभाग",category:"Land",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Minbhawan, Kathmandu",description:"Official land surveying and cadastral information from the federal department.",website:"https://dos.gov.np/",sourceUrl:"https://dos.gov.np/contact-us/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"land-records-department",name:"Department of Land Management and Archive",nameNe:"भूमि व्यवस्थापन तथा अभिलेख विभाग",category:"Land",level:"Federal",province:"Bagmati",district:"Kathmandu",city:"Babarmahal, Kathmandu",description:"Official department information for land management and archival records.",website:"https://dolrm.gov.np/",sourceUrl:"https://www.dolrm.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"kathmandu-metropolitan",name:"Kathmandu Metropolitan City",nameNe:"काठमाडौँ महानगरपालिका",category:"Local Government",level:"Local",province:"Bagmati",district:"Kathmandu",city:"Kathmandu Plaza, Kathmandu",description:"Official Kathmandu Metropolitan City local government website and notices.",website:"https://kathmandu.gov.np/",sourceUrl:"https://kathmandu.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"lalitpur-metropolitan",name:"Lalitpur Metropolitan City",nameNe:"ललितपुर महानगरपालिका",category:"Local Government",level:"Local",province:"Bagmati",district:"Lalitpur",city:"Pulchowk, Lalitpur",description:"Official Lalitpur Metropolitan City website for municipal information and notices.",website:"https://lmc.gov.np/",sourceUrl:"https://lmc.gov.np/en/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"bhaktapur-municipality",name:"Bhaktapur Municipality",nameNe:"भक्तपुर नगरपालिका",category:"Local Government",level:"Local",province:"Bagmati",district:"Bhaktapur",city:"Byasi, Bhaktapur",description:"Official Bhaktapur Municipality website with citizen-service and municipal information.",website:"https://bhaktapurmun.gov.np/",sourceUrl:"https://bhaktapurmun.gov.np/en",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"biratnagar-metropolitan",name:"Biratnagar Metropolitan City",nameNe:"विराटनगर महानगरपालिका",category:"Local Government",level:"Local",province:"Koshi",district:"Morang",city:"Biratnagar, Morang",description:"Official local government homepage, news and municipal information; check the site for current services.",website:"https://biratnagarmun.gov.np/en",sourceUrl:"https://biratnagarmun.gov.np/en",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"janakpurdham-submetro",name:"Janakpurdham Sub-Metropolitan City",nameNe:"जनकपुरधाम उपमहानगरपालिका",category:"Local Government",level:"Local",province:"Madhesh",district:"Dhanusha",city:"Janakpurdham, Dhanusha",description:"Official local government homepage, news and municipal information; check the site for current services.",website:"https://janakpurmun.gov.np/en",sourceUrl:"https://janakpurmun.gov.np/en",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"pokhara-metropolitan",name:"Pokhara Metropolitan City",nameNe:"पोखरा महानगरपालिका",category:"Local Government",level:"Local",province:"Gandaki",district:"Kaski",city:"Pokhara, Kaski",description:"Official local government homepage, news and municipal information; check the site for current services.",website:"https://pokharamun.gov.np/",sourceUrl:"https://pokharamun.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"butwal-submetro",name:"Butwal Sub-Metropolitan City",nameNe:"बुटवल उपमहानगरपालिका",category:"Local Government",level:"Local",province:"Lumbini",district:"Rupandehi",city:"Butwal, Rupandehi",description:"Official local government homepage, news and municipal information; check the site for current services.",website:"https://butwalmun.gov.np/",sourceUrl:"https://butwalmun.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"birendranagar-municipality",name:"Birendranagar Municipality",nameNe:"वीरेन्द्रनगर नगरपालिका",category:"Local Government",level:"Local",province:"Karnali",district:"Surkhet",city:"Birendranagar, Surkhet",description:"Official local government homepage, news and municipal information; check the site for current services.",website:"https://birendranagarmun.gov.np/en",sourceUrl:"https://birendranagarmun.gov.np/en",checkedOn:"2026-10-09",status:"homepage-verified" },
  { id:"dhangadhi-submetro",name:"Dhangadhi Sub-Metropolitan City",nameNe:"धनगढी उपमहानगरपालिका",category:"Local Government",level:"Local",province:"Sudurpashchim",district:"Kailali",city:"Dhangadhi, Kailali",description:"Official local government homepage, news and municipal information; check the site for current services.",website:"https://dhangadhimun.gov.np/",sourceUrl:"https://dhangadhimun.gov.np/",checkedOn:"2026-10-09",status:"homepage-verified" }
];
